#example on how qfm surfaces can be generated
using MID
using MIDViz
#%%

#start by defining the problem
k1 = 0.0019
k2 = 0.0007
k3 = 0.0013
geo = init_geo(R0=4.0)
isl1 = init_island(m0=7, n0=-4, A=k1/7)
isl2 = init_island(m0=5, n0=-3, A=k2/5)
isl3 = init_island(m0=8, n0=-5, A=k3/8) 

isls = [isl1, isl2, isl3]
geo = init_geo(R0=4.0)
prob = init_problem(geo=geo, q=low_shear_qfm_q, isls=isls)
#%%
#generate a Poincare plot to view the chaotic region generated by the overlapping islands
Ntraj = 150;
rlist = collect(LinRange(0.7, 0.95, Ntraj));
#rlist = collect(LinRange(0.1, 1.0, Ntraj));
Nlaps = 500;

poincare_plot(prob, Nlaps, Ntraj, rlist)
#%%
rats1 = lowest_rationals(4, prob.q(0.0)[1], prob.q(1.0)[1])
gl1 = surface_guess(rats1, prob.q)
#changing these numbers doesn't really help remove the spikes
surfs1 = construct_surfaces(rats1, gl1, prob, M=32, N=16);
plot_surfs(surfs1)


